# 1. Identidad (Vital para que pida el archivo correcto al Config Server)
spring.application.name=eureka-server

# 2. Puerto (Forzado localmente para evitar que arranque en 8080)
server.port=8761

# 3. Configuración de Eureka (No quiero que se registre a sí mismo)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# 4. Conexión al Config Server (Importación moderna y robusta)
spring.config.import=optional:configserver:http://localhost:8888